[2025-09-18T05:36:47.110+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-09-18T05:36:47.132+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: example_branch_python_operator_decorator.branching_virtualenv scheduled__2025-09-17T00:00:00+00:00 [queued]>
[2025-09-18T05:36:47.144+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: example_branch_python_operator_decorator.branching_virtualenv scheduled__2025-09-17T00:00:00+00:00 [queued]>
[2025-09-18T05:36:47.145+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2025-09-18T05:36:47.162+0000] {taskinstance.py:2888} INFO - Executing <Task(_BranchPythonVirtualenvDecoratedOperator): branching_virtualenv> on 2025-09-17 00:00:00+00:00
[2025-09-18T05:36:47.172+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=401) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-09-18T05:36:47.175+0000] {standard_task_runner.py:72} INFO - Started process 405 to run task
[2025-09-18T05:36:47.175+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'example_branch_python_operator_decorator', 'branching_virtualenv', 'scheduled__2025-09-17T00:00:00+00:00', '--job-id', '45', '--raw', '--subdir', '/home/***/.local/lib/python3.12/site-packages/***/example_dags/example_branch_operator_decorator.py', '--cfg-path', '/tmp/tmprnrwck90']
[2025-09-18T05:36:47.177+0000] {standard_task_runner.py:105} INFO - Job 45: Subtask branching_virtualenv
[2025-09-18T05:36:47.278+0000] {task_command.py:467} INFO - Running <TaskInstance: example_branch_python_operator_decorator.branching_virtualenv scheduled__2025-09-17T00:00:00+00:00 [running]> on host 7f8c5cf1dc7b
[2025-09-18T05:36:47.426+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='example_branch_python_operator_decorator' AIRFLOW_CTX_TASK_ID='branching_virtualenv' AIRFLOW_CTX_EXECUTION_DATE='2025-09-17T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-09-17T00:00:00+00:00'
[2025-09-18T05:36:47.431+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-09-18T05:36:47.432+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-09-18T05:36:47.432+0000] {logging_mixin.py:190} INFO - Current task name:branching_virtualenv state:running start_date:2025-09-18 05:36:47.133519+00:00
[2025-09-18T05:36:47.433+0000] {logging_mixin.py:190} INFO - Dag name:example_branch_python_operator_decorator and current dag run status:running
[2025-09-18T05:36:47.433+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-09-18T05:36:47.447+0000] {python.py:809} INFO - Python virtual environment will be cached in /tmp/venv-ebe3c33d
[2025-09-18T05:36:47.452+0000] {process_utils.py:186} INFO - Executing cmd: /home/***/.local/bin/python -m virtualenv /tmp/venv-ebe3c33d --system-site-packages --python=python
[2025-09-18T05:36:47.454+0000] {process_utils.py:190} INFO - Output:
[2025-09-18T05:36:49.245+0000] {process_utils.py:194} INFO - created virtual environment CPython3.12.6.final.0-64 in 844ms
[2025-09-18T05:36:49.251+0000] {process_utils.py:194} INFO -   creator CPython3Posix(dest=/tmp/venv-ebe3c33d, clear=False, no_vcs_ignore=False, global=True)
[2025-09-18T05:36:49.252+0000] {process_utils.py:194} INFO -   seeder FromAppData(download=False, pip=bundle, via=copy, app_data_dir=/home/***/.local/share/virtualenv)
[2025-09-18T05:36:49.254+0000] {process_utils.py:194} INFO -     added seed packages: pip==24.2
[2025-09-18T05:36:49.255+0000] {process_utils.py:194} INFO -   activators BashActivator,CShellActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator
[2025-09-18T05:36:49.314+0000] {process_utils.py:186} INFO - Executing cmd: /tmp/venv-ebe3c33d/bin/pip install -r /tmp/venv-ebe3c33d/requirements.txt
[2025-09-18T05:36:49.316+0000] {process_utils.py:190} INFO - Output:
[2025-09-18T05:36:53.369+0000] {process_utils.py:194} INFO - Collecting numpy~=1.24.4 (from -r /tmp/venv-ebe3c33d/requirements.txt (line 1))
[2025-09-18T05:36:54.156+0000] {process_utils.py:194} INFO -   Downloading numpy-1.24.4.tar.gz (10.9 MB)
[2025-09-18T05:36:57.265+0000] {process_utils.py:194} INFO -      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.9/10.9 MB 3.6 MB/s eta 0:00:00
[2025-09-18T05:36:58.898+0000] {process_utils.py:194} INFO -   Installing build dependencies: started
[2025-09-18T05:37:07.577+0000] {process_utils.py:194} INFO -   Installing build dependencies: finished with status 'done'
[2025-09-18T05:37:07.580+0000] {process_utils.py:194} INFO -   Getting requirements to build wheel: started
[2025-09-18T05:37:07.788+0000] {process_utils.py:194} INFO -   Getting requirements to build wheel: finished with status 'done'
[2025-09-18T05:37:08.120+0000] {process_utils.py:194} INFO - 
[2025-09-18T05:37:08.121+0000] {process_utils.py:194} INFO - [notice] A new release of pip is available: 24.2 -> 25.2
[2025-09-18T05:37:08.122+0000] {process_utils.py:194} INFO - [notice] To update, run: python -m pip install --upgrade pip
[2025-09-18T05:37:08.128+0000] {process_utils.py:194} INFO - ERROR: Exception:
[2025-09-18T05:37:08.129+0000] {process_utils.py:194} INFO - Traceback (most recent call last):
[2025-09-18T05:37:08.131+0000] {process_utils.py:194} INFO -   File "/tmp/venv-ebe3c33d/lib/python3.12/site-packages/pip/_internal/cli/base_command.py", line 105, in _run_wrapper
[2025-09-18T05:37:08.132+0000] {process_utils.py:194} INFO -     status = _inner_run()
[2025-09-18T05:37:08.133+0000] {process_utils.py:194} INFO -              ^^^^^^^^^^^^
[2025-09-18T05:37:08.134+0000] {process_utils.py:194} INFO -   File "/tmp/venv-ebe3c33d/lib/python3.12/site-packages/pip/_internal/cli/base_command.py", line 96, in _inner_run
[2025-09-18T05:37:08.134+0000] {process_utils.py:194} INFO -     return self.run(options, args)
[2025-09-18T05:37:08.135+0000] {process_utils.py:194} INFO -            ^^^^^^^^^^^^^^^^^^^^^^^
[2025-09-18T05:37:08.136+0000] {process_utils.py:194} INFO -   File "/tmp/venv-ebe3c33d/lib/python3.12/site-packages/pip/_internal/cli/req_command.py", line 67, in wrapper
[2025-09-18T05:37:08.137+0000] {process_utils.py:194} INFO -     return func(self, options, args)
[2025-09-18T05:37:08.137+0000] {process_utils.py:194} INFO -            ^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-09-18T05:37:08.138+0000] {process_utils.py:194} INFO -   File "/tmp/venv-ebe3c33d/lib/python3.12/site-packages/pip/_internal/commands/install.py", line 379, in run
[2025-09-18T05:37:08.139+0000] {process_utils.py:194} INFO -     requirement_set = resolver.resolve(
[2025-09-18T05:37:08.140+0000] {process_utils.py:194} INFO -                       ^^^^^^^^^^^^^^^^^
[2025-09-18T05:37:08.141+0000] {process_utils.py:194} INFO -   File "/tmp/venv-ebe3c33d/lib/python3.12/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 95, in resolve
[2025-09-18T05:37:08.141+0000] {process_utils.py:194} INFO -     result = self._result = resolver.resolve(
[2025-09-18T05:37:08.142+0000] {process_utils.py:194} INFO -                             ^^^^^^^^^^^^^^^^^
[2025-09-18T05:37:08.143+0000] {process_utils.py:194} INFO -   File "/tmp/venv-ebe3c33d/lib/python3.12/site-packages/pip/_vendor/resolvelib/resolvers.py", line 546, in resolve
[2025-09-18T05:37:08.144+0000] {process_utils.py:194} INFO -     state = resolution.resolve(requirements, max_rounds=max_rounds)
[2025-09-18T05:37:08.145+0000] {process_utils.py:194} INFO -             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-09-18T05:37:08.146+0000] {process_utils.py:194} INFO -   File "/tmp/venv-ebe3c33d/lib/python3.12/site-packages/pip/_vendor/resolvelib/resolvers.py", line 397, in resolve
[2025-09-18T05:37:08.146+0000] {process_utils.py:194} INFO -     self._add_to_criteria(self.state.criteria, r, parent=None)
[2025-09-18T05:37:08.148+0000] {process_utils.py:194} INFO -   File "/tmp/venv-ebe3c33d/lib/python3.12/site-packages/pip/_vendor/resolvelib/resolvers.py", line 173, in _add_to_criteria
[2025-09-18T05:37:08.149+0000] {process_utils.py:194} INFO -     if not criterion.candidates:
[2025-09-18T05:37:08.150+0000] {process_utils.py:194} INFO -            ^^^^^^^^^^^^^^^^^^^^
[2025-09-18T05:37:08.151+0000] {process_utils.py:194} INFO -   File "/tmp/venv-ebe3c33d/lib/python3.12/site-packages/pip/_vendor/resolvelib/structs.py", line 156, in __bool__
[2025-09-18T05:37:08.152+0000] {process_utils.py:194} INFO -     return bool(self._sequence)
[2025-09-18T05:37:08.153+0000] {process_utils.py:194} INFO -            ^^^^^^^^^^^^^^^^^^^^
[2025-09-18T05:37:08.154+0000] {process_utils.py:194} INFO -   File "/tmp/venv-ebe3c33d/lib/python3.12/site-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 174, in __bool__
[2025-09-18T05:37:08.154+0000] {process_utils.py:194} INFO -     return any(self)
[2025-09-18T05:37:08.155+0000] {process_utils.py:194} INFO -            ^^^^^^^^^
[2025-09-18T05:37:08.156+0000] {process_utils.py:194} INFO -   File "/tmp/venv-ebe3c33d/lib/python3.12/site-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 162, in <genexpr>
[2025-09-18T05:37:08.157+0000] {process_utils.py:194} INFO -     return (c for c in iterator if id(c) not in self._incompatible_ids)
[2025-09-18T05:37:08.157+0000] {process_utils.py:194} INFO -                        ^^^^^^^^
[2025-09-18T05:37:08.158+0000] {process_utils.py:194} INFO -   File "/tmp/venv-ebe3c33d/lib/python3.12/site-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 53, in _iter_built
[2025-09-18T05:37:08.159+0000] {process_utils.py:194} INFO -     candidate = func()
[2025-09-18T05:37:08.160+0000] {process_utils.py:194} INFO -                 ^^^^^^
[2025-09-18T05:37:08.161+0000] {process_utils.py:194} INFO -   File "/tmp/venv-ebe3c33d/lib/python3.12/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 186, in _make_candidate_from_link
[2025-09-18T05:37:08.161+0000] {process_utils.py:194} INFO -     base: Optional[BaseCandidate] = self._make_base_candidate_from_link(
[2025-09-18T05:37:08.162+0000] {process_utils.py:194} INFO -                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-09-18T05:37:08.164+0000] {process_utils.py:194} INFO -   File "/tmp/venv-ebe3c33d/lib/python3.12/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 232, in _make_base_candidate_from_link
[2025-09-18T05:37:08.165+0000] {process_utils.py:194} INFO -     self._link_candidate_cache[link] = LinkCandidate(
[2025-09-18T05:37:08.166+0000] {process_utils.py:194} INFO -                                        ^^^^^^^^^^^^^^
[2025-09-18T05:37:08.167+0000] {process_utils.py:194} INFO -   File "/tmp/venv-ebe3c33d/lib/python3.12/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 303, in __init__
[2025-09-18T05:37:08.167+0000] {process_utils.py:194} INFO -     super().__init__(
[2025-09-18T05:37:08.168+0000] {process_utils.py:194} INFO -   File "/tmp/venv-ebe3c33d/lib/python3.12/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 158, in __init__
[2025-09-18T05:37:08.170+0000] {process_utils.py:194} INFO -     self.dist = self._prepare()
[2025-09-18T05:37:08.171+0000] {process_utils.py:194} INFO -                 ^^^^^^^^^^^^^^^
[2025-09-18T05:37:08.172+0000] {process_utils.py:194} INFO -   File "/tmp/venv-ebe3c33d/lib/python3.12/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 235, in _prepare
[2025-09-18T05:37:08.173+0000] {process_utils.py:194} INFO -     dist = self._prepare_distribution()
[2025-09-18T05:37:08.177+0000] {process_utils.py:194} INFO -            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-09-18T05:37:08.179+0000] {process_utils.py:194} INFO -   File "/tmp/venv-ebe3c33d/lib/python3.12/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 314, in _prepare_distribution
[2025-09-18T05:37:08.182+0000] {process_utils.py:194} INFO -     return preparer.prepare_linked_requirement(self._ireq, parallel_builds=True)
[2025-09-18T05:37:08.183+0000] {process_utils.py:194} INFO -            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-09-18T05:37:08.186+0000] {process_utils.py:194} INFO -   File "/tmp/venv-ebe3c33d/lib/python3.12/site-packages/pip/_internal/operations/prepare.py", line 527, in prepare_linked_requirement
[2025-09-18T05:37:08.187+0000] {process_utils.py:194} INFO -     return self._prepare_linked_requirement(req, parallel_builds)
[2025-09-18T05:37:08.189+0000] {process_utils.py:194} INFO -            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-09-18T05:37:08.190+0000] {process_utils.py:194} INFO -   File "/tmp/venv-ebe3c33d/lib/python3.12/site-packages/pip/_internal/operations/prepare.py", line 642, in _prepare_linked_requirement
[2025-09-18T05:37:08.192+0000] {process_utils.py:194} INFO -     dist = _get_prepared_distribution(
[2025-09-18T05:37:08.193+0000] {process_utils.py:194} INFO -            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-09-18T05:37:08.194+0000] {process_utils.py:194} INFO -   File "/tmp/venv-ebe3c33d/lib/python3.12/site-packages/pip/_internal/operations/prepare.py", line 72, in _get_prepared_distribution
[2025-09-18T05:37:08.196+0000] {process_utils.py:194} INFO -     abstract_dist.prepare_distribution_metadata(
[2025-09-18T05:37:08.197+0000] {process_utils.py:194} INFO -   File "/tmp/venv-ebe3c33d/lib/python3.12/site-packages/pip/_internal/distributions/sdist.py", line 56, in prepare_distribution_metadata
[2025-09-18T05:37:08.198+0000] {process_utils.py:194} INFO -     self._install_build_reqs(finder)
[2025-09-18T05:37:08.199+0000] {process_utils.py:194} INFO -   File "/tmp/venv-ebe3c33d/lib/python3.12/site-packages/pip/_internal/distributions/sdist.py", line 126, in _install_build_reqs
[2025-09-18T05:37:08.201+0000] {process_utils.py:194} INFO -     build_reqs = self._get_build_requires_wheel()
[2025-09-18T05:37:08.201+0000] {process_utils.py:194} INFO -                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-09-18T05:37:08.203+0000] {process_utils.py:194} INFO -   File "/tmp/venv-ebe3c33d/lib/python3.12/site-packages/pip/_internal/distributions/sdist.py", line 103, in _get_build_requires_wheel
[2025-09-18T05:37:08.204+0000] {process_utils.py:194} INFO -     return backend.get_requires_for_build_wheel()
[2025-09-18T05:37:08.205+0000] {process_utils.py:194} INFO -            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-09-18T05:37:08.206+0000] {process_utils.py:194} INFO -   File "/tmp/venv-ebe3c33d/lib/python3.12/site-packages/pip/_internal/utils/misc.py", line 706, in get_requires_for_build_wheel
[2025-09-18T05:37:08.211+0000] {process_utils.py:194} INFO -     return super().get_requires_for_build_wheel(config_settings=cs)
[2025-09-18T05:37:08.215+0000] {process_utils.py:194} INFO -            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-09-18T05:37:08.216+0000] {process_utils.py:194} INFO -   File "/tmp/venv-ebe3c33d/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_impl.py", line 166, in get_requires_for_build_wheel
[2025-09-18T05:37:08.217+0000] {process_utils.py:194} INFO -     return self._call_hook('get_requires_for_build_wheel', {
[2025-09-18T05:37:08.218+0000] {process_utils.py:194} INFO -            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-09-18T05:37:08.220+0000] {process_utils.py:194} INFO -   File "/tmp/venv-ebe3c33d/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_impl.py", line 321, in _call_hook
[2025-09-18T05:37:08.224+0000] {process_utils.py:194} INFO -     raise BackendUnavailable(data.get('traceback', ''))
[2025-09-18T05:37:08.226+0000] {process_utils.py:194} INFO - pip._vendor.pyproject_hooks._impl.BackendUnavailable: Traceback (most recent call last):
[2025-09-18T05:37:08.228+0000] {process_utils.py:194} INFO -   File "/tmp/venv-ebe3c33d/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 77, in _build_backend
[2025-09-18T05:37:08.234+0000] {process_utils.py:194} INFO -     obj = import_module(mod_path)
[2025-09-18T05:37:08.236+0000] {process_utils.py:194} INFO -           ^^^^^^^^^^^^^^^^^^^^^^^
[2025-09-18T05:37:08.237+0000] {process_utils.py:194} INFO -   File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
[2025-09-18T05:37:08.239+0000] {process_utils.py:194} INFO -     return _bootstrap._gcd_import(name[level:], package, level)
[2025-09-18T05:37:08.241+0000] {process_utils.py:194} INFO -            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-09-18T05:37:08.242+0000] {process_utils.py:194} INFO -   File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
[2025-09-18T05:37:08.244+0000] {process_utils.py:194} INFO -   File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
[2025-09-18T05:37:08.247+0000] {process_utils.py:194} INFO -   File "<frozen importlib._bootstrap>", line 1310, in _find_and_load_unlocked
[2025-09-18T05:37:08.249+0000] {process_utils.py:194} INFO -   File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
[2025-09-18T05:37:08.250+0000] {process_utils.py:194} INFO -   File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
[2025-09-18T05:37:08.251+0000] {process_utils.py:194} INFO -   File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
[2025-09-18T05:37:08.253+0000] {process_utils.py:194} INFO -   File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
[2025-09-18T05:37:08.254+0000] {process_utils.py:194} INFO -   File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
[2025-09-18T05:37:08.255+0000] {process_utils.py:194} INFO -   File "<frozen importlib._bootstrap_external>", line 995, in exec_module
[2025-09-18T05:37:08.257+0000] {process_utils.py:194} INFO -   File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
[2025-09-18T05:37:08.258+0000] {process_utils.py:194} INFO -   File "/tmp/pip-build-env-_dwokd04/overlay/lib/python3.12/site-packages/setuptools/__init__.py", line 10, in <module>
[2025-09-18T05:37:08.259+0000] {process_utils.py:194} INFO -     import distutils.core
[2025-09-18T05:37:08.260+0000] {process_utils.py:194} INFO - ModuleNotFoundError: No module named 'distutils'
[2025-09-18T05:37:08.261+0000] {process_utils.py:194} INFO - 
[2025-09-18T05:37:08.598+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 852, in _ensure_venv_cache_exists
    self._prepare_venv(venv_path)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 769, in _prepare_venv
    prepare_virtualenv(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/python_virtualenv.py", line 119, in prepare_virtualenv
    execute_in_subprocess(pip_cmd)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/process_utils.py", line 175, in execute_in_subprocess
    execute_in_subprocess_with_kwargs(cmd, cwd=cwd, env=env)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/process_utils.py", line 198, in execute_in_subprocess_with_kwargs
    raise subprocess.CalledProcessError(exit_code, cmd)
subprocess.CalledProcessError: Command '['/tmp/venv-ebe3c33d/bin/pip', 'install', '-r', '/tmp/venv-ebe3c33d/requirements.txt']' returned non-zero exit status 2.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/base.py", line 266, in execute
    return_value = super().execute(context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 901, in execute
    return self.do_branch(context, super().execute(context))
                                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 505, in execute
    return super().execute(context=serializable_context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 862, in execute_callable
    venv_path = self._ensure_venv_cache_exists(Path(self.venv_cache_path))
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 856, in _ensure_venv_cache_exists
    raise AirflowException(f"Unable to create new virtual environment in {venv_path}") from e
airflow.exceptions.AirflowException: Unable to create new virtual environment in /tmp/venv-ebe3c33d
[2025-09-18T05:37:08.611+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-09-18T05:37:08.612+0000] {logging_mixin.py:190} INFO - Task start:2025-09-18 05:36:47.133519+00:00 end:2025-09-18 05:37:08.610820+00:00 duration:21.477301
[2025-09-18T05:37:08.612+0000] {logging_mixin.py:190} INFO - Task:<Task(_BranchPythonVirtualenvDecoratedOperator): branching_virtualenv> dag:<DAG: example_branch_python_operator_decorator> dagrun:<DagRun example_branch_python_operator_decorator @ 2025-09-17 00:00:00+00:00: scheduled__2025-09-17T00:00:00+00:00, state:running, queued_at: 2025-09-18 05:36:18.027954+00:00. externally triggered: False>
[2025-09-18T05:37:08.613+0000] {logging_mixin.py:190} INFO - Failure caused by Unable to create new virtual environment in /tmp/venv-ebe3c33d
[2025-09-18T05:37:08.614+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=example_branch_python_operator_decorator, task_id=branching_virtualenv, run_id=scheduled__2025-09-17T00:00:00+00:00, execution_date=20250917T000000, start_date=20250918T053647, end_date=20250918T053708
[2025-09-18T05:37:08.634+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-09-18T05:37:08.636+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 45 for task branching_virtualenv (Unable to create new virtual environment in /tmp/venv-ebe3c33d; 405)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 852, in _ensure_venv_cache_exists
    self._prepare_venv(venv_path)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 769, in _prepare_venv
    prepare_virtualenv(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/python_virtualenv.py", line 119, in prepare_virtualenv
    execute_in_subprocess(pip_cmd)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/process_utils.py", line 175, in execute_in_subprocess
    execute_in_subprocess_with_kwargs(cmd, cwd=cwd, env=env)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/process_utils.py", line 198, in execute_in_subprocess_with_kwargs
    raise subprocess.CalledProcessError(exit_code, cmd)
subprocess.CalledProcessError: Command '['/tmp/venv-ebe3c33d/bin/pip', 'install', '-r', '/tmp/venv-ebe3c33d/requirements.txt']' returned non-zero exit status 2.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/base.py", line 266, in execute
    return_value = super().execute(context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 901, in execute
    return self.do_branch(context, super().execute(context))
                                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 505, in execute
    return super().execute(context=serializable_context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 862, in execute_callable
    venv_path = self._ensure_venv_cache_exists(Path(self.venv_cache_path))
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 856, in _ensure_venv_cache_exists
    raise AirflowException(f"Unable to create new virtual environment in {venv_path}") from e
airflow.exceptions.AirflowException: Unable to create new virtual environment in /tmp/venv-ebe3c33d
[2025-09-18T05:37:08.678+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-09-18T05:37:08.753+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-09-18T05:37:08.761+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
